version: '3.4'

services:
  fazaaulia:
    image: fazaaulia
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
  # redis:
  #   image: 'redis'
  #   ports:
  #     - '6379:6379'
