version: '3.4'

services:
  fazaaulia:
    depends_on:
      - redis
    image: fazaaulia
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
  redis:
    image: 'redis'
    expose:
      - 6379
